name: trigger

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Print my statement
        run: echo "This trigger happened"
